addons:
  sonarqube: true

language: java
install: ant deps

branches:
  only:
  - master

jdk:
  - oraclejdk7

script: ant build

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavutil51
  - sudo apt-get install -y libavformat53
  - sudo apt-get install -y libavcodec53

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

addons:
  apt:
    packages:
      - oracle-java7-installer

after_success:
  - bash <(curl -s https://codecov.io/bash)
